---
abstract: 'easily choose between different version-specific implementations'
author:
  - 'Belden Lyman <belden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: provide
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/belden/perl-provide/issues
version: 0.02
